# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup build runner
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build and push Jessie image
          # shell: /bin/bash
          command: |
            # docker build -t eugenesia/phpfarm:jessie -t eugenesia/phpfarm:latest -f Dockerfile-Jessie .
            docker pull eugenesia/phpfarm:jessie
            docker pull eugenesia/phpfarm:latest
            # docker push eugenesia/phpfarm:jessie
            # docker push eugenesia/phpfarm:latest
      - run:
          name: Build and push Wheezy image
          # shell: /bin/bash
          command: |
            # docker build -t eugenesia/phpfarm:wheezy -t eugenesia/phpfarm:latest -f Dockerfile-Wheezy .
            docker pull eugenesia/phpfarm:wheezy
            docker push eugenesia/phpfarm:wheezy

